### PR TITLE
Incall fix for samsung msm8916 NXP amp anyone here?

### PR DESCRIPTION
**Pull request by ghost**
Change-Id: I88aca4e1231a38a1366fe818b17de924673e7cf4

This takes effect only if you add ro.telephony.samsung.realcall=true to build.prop so dosen't affect another devices

### CODE REVIEW

**Comment by ghost** [comment]
Someoane here?

**Comment by westcripp** [comment]
Tested ??

**Comment by SoUnd001** [comment]
Yes is tested also AOKP AEX and Hexagon has this commit

**Comment by ghost** [comment]
@westcripp Yes tested Aokp , Aex , Hexagon , Cosmic has this commit

**Pull request merged**
